/**
 * @file DualKeyTable.hpp
 * @author osterhoutan (osterhoutan+scabbard@gmail.com)
 * @brief a data structure that allows for a dual key lookup of a entry in a table, 
 *        but also to get all entries just under one key.
 *        \em NOTE: this data structure was generated by Claude Sonnet 5
 *        
 *        A single-table data structure with a composite two-integer
 *        primary key, supporting fast lookups by either key alone.
 *
 *        Behaves like a single SQL table where:
 *        - `(key1, key2)` together are the unique primary key. insert()/emplace()
 *          on an existing `(key1, key2)` replace that row's data (like SQL's
 *          `INSERT ... ON CONFLICT ... DO UPDATE` / `insert_or_assign`) rather
 *          than failing or creating a duplicate.
 *        - key1 alone can repeat across many rows -- findByKey1() returns all matches.
 *        - key2 alone can repeat across many rows -- findByKey2() returns all matches.
 *
 *        ### Time Complexity 
 *        (average case, hash maps assumed well distributed)
 * 
 *        | Operation         | Complexity |
 *        |-------------------|------------|
 *        | insert()          | O(1) |
 *        | emplace()         | O(1) |
 *        | find(k1, k2)      | O(1) |
 *        | findByKey1(k1)    | O(1) ; O(m) to iterate all matches, no allocation |
 *        | findByKey2(k2)    | O(1) ; O(m) to iterate all matches, no allocation |
 *        | erase(k1, k2)     | O(1) amortized (swap-and-pop; a couple of small vector removals) |
 *        | clear()           | O(n) |
 *        | operator[]        | O(1) (find-or-default-construct, like `std::unordered_map`) |
 *        | allKeys1()        | O(1) to obtain the view; iterating it is O(u), u = distinct keys in use |
 *        | allKeys2()        | O(1) to obtain the view; iterating it is O(u), u = distinct keys in use |
 * 
 *        ### Space complexity
 *        
 *        Overall: O(n)
 * 
 * @version alpha 0.0.1
 * @date 2026-08-27
 * 
 */

#pragma once

#include <vector>
#include <unordered_map>
#include <algorithm>
#include <cstdint>
#include <optional>
#include <utility>
#include <type_traits>

namespace scabbard{
namespace rtl {

/**
 * @class DualKeyTableKeyView
 *
 * @brief A read-only, non-owning view over the *keys* of a `std::unordered_map<K,
 *        std::vector<std::size_t>>` -- the shape DualKeyTable's per-key indexes use
 *        internally.
 *
 *        Iterating a DualKeyTableKeyView yields `const K&` -- just the key, never the
 *        index vector -- without copying any keys into a new container. This class backs
 *        DualKeyTable::allKeys1() and DualKeyTable::allKeys2().
 *
 * @tparam K The key type being viewed.
 *
 * @note **Lifetime**: a DualKeyTableKeyView holds a reference to the table's internal
 *       index map, so it is only valid as long as the DualKeyTable it came from is alive,
 *       and it follows the same iterator-invalidation rules as the underlying
 *       `std::unordered_map` -- don't insert/erase on the table while iterating a view
 *       obtained from it.
 */
template <typename K>
class DualKeyTableKeyView {
public:
    /**
     * @class const_iterator
     *
     * @brief Forward, read-only iterator over the distinct keys in the wrapped index map.
     *
     *        Dereferencing yields `const K&`, never the underlying `std::pair<const K,
     *        std::vector<std::size_t>>` -- the index-vector half is never exposed through this
     *        iterator.
     */
    class const_iterator {
    public:
        using inner_iterator = typename std::unordered_map<K, std::vector<std::size_t>>::const_iterator;
        using iterator_category = std::forward_iterator_tag;
        using value_type = K;
        using difference_type = std::ptrdiff_t;
        using pointer = const K*;
        using reference = const K&;

        explicit const_iterator(inner_iterator it) : it_(it) {}

        /**
         * @brief Returns the key at the current position (read-only).
         *
         * @return A const reference to the current key.
         */
        reference operator*() const { return it_->first; }

        /**
         * @brief Returns a pointer to the key at the current position (read-only).
         *
         * @return A const pointer to the current key.
         */
        pointer operator->() const { return &it_->first; }

        /**
         * @brief Advances to the next distinct key (pre-increment).
         *
         * @return A reference to this iterator, now advanced.
         */
        const_iterator& operator++() { ++it_; return *this; }

        /**
         * @brief Advances to the next distinct key (post-increment).
         *
         * @return A copy of the iterator as it was before advancing.
         */
        const_iterator operator++(int) { const_iterator tmp = *this; ++it_; return tmp; }

        /**
         * @brief Compares two iterators for equality.
         *
         * @param o The iterator to compare against.
         *
         * @return `true` if both iterators refer to the same position.
         */
        bool operator==(const const_iterator& o) const { return it_ == o.it_; }

        /**
         * @brief Compares two iterators for inequality.
         *
         * @param o The iterator to compare against.
         *
         * @return `true` if the iterators refer to different positions.
         */
        bool operator!=(const const_iterator& o) const { return it_ != o.it_; }

    private:
        inner_iterator it_;
    };

    /**
     * @brief Wraps an existing index map. Does not copy or take ownership; the referenced map
     *        must outlive this view.
     *
     * @param map The `std::unordered_map<K, std::vector<std::size_t>>` to view.
     */
    explicit DualKeyTableKeyView(const std::unordered_map<K, std::vector<std::size_t>>& map) : map_(map) {}

    /**
     * @brief Returns an iterator to the first distinct key.
     *
     * @return A const_iterator to the first key. Order is unspecified.
     */
    const_iterator begin() const { return const_iterator(map_.begin()); }

    /**
     * @brief Returns an iterator one past the last distinct key.
     *
     * @return The end const_iterator.
     */
    const_iterator end() const { return const_iterator(map_.end()); }

    /**
     * @brief Returns the number of distinct keys currently in the view.
     *
     * @return The key count.
     */
    std::size_t size() const { return map_.size(); }

    /**
     * @brief Checks whether the view has any keys.
     *
     * @return `true` if there are no keys to view.
     */
    bool empty() const { return map_.empty(); }

private:
    const std::unordered_map<K, std::vector<std::size_t>>& map_;
};

/**
 * @class DualKeyTableEntryView
 *
 * @brief A read-only, non-owning view over the rows that share a given key1 or key2 value
 *        -- the result of DualKeyTable::findByKey1() / findByKey2().
 *
 *        Iterating this view walks the underlying per-key index vector directly and
 *        dereferences each stored row index straight into the table's row storage: no new
 *        container is allocated, and no Entry pointers are copied anywhere, to produce or
 *        return the view. Obtaining the view is O(1); the O(m) cost of visiting m matching
 *        rows only happens if and when you actually iterate.
 *
 *        The view exposes nothing but read-only (or, for the mutable overload,
 *        row-mutating) iteration -- there is no way to add, remove, or reorder entries
 *        through it, so it cannot be used to corrupt the table's internal indexes.
 *
 * @tparam EntryT Either `Entry` (mutable view, yields `Entry&`) or `const Entry`
 *                (read-only view, yields `const Entry&`).
 *
 * @note **Lifetime**: like DualKeyTableKeyView, this view borrows from the table it came
 *       from, so it is only valid as long as that DualKeyTable is alive, and it follows
 *       the same iterator-invalidation rules as the underlying
 *       `std::vector`/`std::unordered_map` -- don't insert/erase on the table while
 *       iterating a view obtained from it.
 */
template <typename EntryT>
class DualKeyTableEntryView {
public:
    using StorageVector = std::vector<typename std::remove_const<EntryT>::type>;
    using StoragePtr = typename std::conditional<std::is_const<EntryT>::value,
                                                  const StorageVector*, StorageVector*>::type;

    /**
     * @class iterator
     *
     * @brief Forward iterator over the rows in a DualKeyTableEntryView, yielding `EntryT&`
     *        (either mutable or read-only, depending on EntryT).
     */
    class iterator {
    public:
        using inner_iterator = std::vector<std::size_t>::const_iterator;
        using iterator_category = std::forward_iterator_tag;
        using value_type = EntryT;
        using difference_type = std::ptrdiff_t;
        using pointer = EntryT*;
        using reference = EntryT&;

        iterator(inner_iterator it, StoragePtr storage) : it_(it), storage_(storage) {}

        /**
         * @brief Returns the row at the current position.
         *
         * @return A reference to the current Entry.
         */
        reference operator*() const { return (*storage_)[*it_]; }

        /**
         * @brief Returns a pointer to the row at the current position.
         *
         * @return A pointer to the current Entry.
         */
        pointer operator->() const { return &(*storage_)[*it_]; }

        /**
         * @brief Advances to the next matching row (pre-increment).
         *
         * @return A reference to this iterator, now advanced.
         */
        iterator& operator++() { ++it_; return *this; }

        /**
         * @brief Advances to the next matching row (post-increment).
         *
         * @return A copy of the iterator as it was before advancing.
         */
        iterator operator++(int) { iterator tmp = *this; ++it_; return tmp; }

        /**
         * @brief Compares two iterators for equality.
         *
         * @param o The iterator to compare against.
         *
         * @return `true` if both iterators refer to the same position.
         */
        bool operator==(const iterator& o) const { return it_ == o.it_; }

        /**
         * @brief Compares two iterators for inequality.
         *
         * @param o The iterator to compare against.
         *
         * @return `true` if the iterators refer to different positions.
         */
        bool operator!=(const iterator& o) const { return it_ != o.it_; }

    private:
        inner_iterator it_;
        StoragePtr storage_;
    };

    /**
     * @brief Constructs an empty view, for the "no rows matched this key" case -- `begin() ==
     *        end()` and `size() == 0`.
     */
    DualKeyTableEntryView() : indices_(&emptyIndices()), storage_(nullptr) {}

    /**
     * @brief Wraps an existing per-key index vector and the table's row storage. Does not copy
     *        either; both must outlive this view.
     *
     * @param indices The matching rows' indices into `storage`.
     *
     * @param storage Pointer to the table's row storage.
     */
    DualKeyTableEntryView(const std::vector<std::size_t>& indices, StoragePtr storage)
        : indices_(&indices), storage_(storage) {}

    /**
     * @brief Returns an iterator to the first matching row.
     *
     * @return An iterator to the first row. Order matches the underlying index vector.
     */
    iterator begin() const { return iterator(indices_->begin(), storage_); }

    /**
     * @brief Returns an iterator one past the last matching row.
     *
     * @return The end iterator.
     */
    iterator end() const { return iterator(indices_->end(), storage_); }

    /**
     * @brief Returns the number of matching rows.
     *
     * @return The row count.
     */
    std::size_t size() const { return indices_->size(); }

    /**
     * @brief Checks whether any rows matched.
     *
     * @return `true` if no rows matched.
     */
    bool empty() const { return indices_->empty(); }

private:
    static const std::vector<std::size_t>& emptyIndices() {
        static const std::vector<std::size_t> empty;
        return empty;
    }
    const std::vector<std::size_t>* indices_;
    StoragePtr storage_;
};

/**
 * @class DualKeyTable
 *
 * @brief A single-table data structure with a composite two-integer primary key,
 *        supporting fast lookups by either key alone.
 *
 *        Behaves like a single SQL table where:
 *
 *          - `(key1, key2)` together are the unique primary key. insert()/emplace()
 *            on an existing `(key1, key2)` replace that row's data (like SQL's
 *            `INSERT ... ON CONFLICT ... DO UPDATE` / `insert_or_assign`) rather
 *            than failing or creating a duplicate.
 *          - key1 alone can repeat across many rows -- findByKey1() returns all matches.
 *          - key2 alone can repeat across many rows -- findByKey2() returns all matches.
 *
 *        ### Complexity (average case, hash maps assumed well distributed)
 *        | Operation             | Complexity |
 *        |------------------------|------------|
 *        | insert()               | O(1) |
 *        | emplace()              | O(1) |
 *        | find(k1, k2)           | O(1) |
 *        | findByKey1(k1)         | O(1) to obtain the view; O(m) to iterate all matches, no allocation |
 *        | findByKey2(k2)         | O(1) to obtain the view; O(m) to iterate all matches, no allocation |
 *        | erase(k1, k2)          | O(1) amortized (swap-and-pop; a couple of small vector removals) |
 *        | clear()                | O(n) |
 *        | operator[]             | O(1) (find-or-default-construct, like `std::unordered_map`) |
 *        | allKeys1()/allKeys2()  | O(1) to obtain the view; iterating it is O(u), u = distinct keys in use |
 *
 * @tparam K1 Type of the first key. Must be an integer type (any size or signedness),
 *            enforced by `static_assert`.
 *
 * @tparam K2 Type of the second key. Same constraint as K1. K1 and K2 do not need to be
 *            the same type.
 *
 * @tparam T The row payload/data type stored alongside each `(key1, key2)`.
 *
 * @note Storage is a single contiguous `std::vector<Entry>`, so iterating all rows, or
 *       scanning matches, is cache-friendly. Pointers/references into the table are
 *       invalidated by insert() (the vector may reallocate) and by erase() (the last
 *       element gets moved into the erased slot). If you need stable addresses across
 *       mutation, change `storage_` to `std::deque<Entry>` -- everything else still works
 *       unmodified.
 *
 *        @code
 *            struct Row { std::string name; double amount; };
 *
 *            DualKeyTable<int, int, Row> table;
 *            table.insert(1, 100, Row{"alice", 42.5});
 *            table.insert(1, 200, Row{"bob",   17.0});
 *
 *            if (auto* e = table.find(1, 100)) { ... }        // exact row
 *            for (auto* e : table.findByKey1(1)) { ... }       // all rows with key1 == 1
 *            table[9][900] = Row{"gina", 1.0};                 // insert-or-get via operator[]
 *            for (int k1 : table.allKeys1()) { ... }           // every distinct key1 in use
 *        @endcode
 */
template <typename K1, typename K2, typename T>
class DualKeyTable {
    static_assert(std::is_integral<K1>::value, "K1 must be an integer type (any size/signedness)");
    static_assert(std::is_integral<K2>::value, "K2 must be an integer type (any size/signedness)");

public:
    /**
     * @struct Entry
     *
     * @brief A single row: its two keys plus the associated data payload.
     */
    struct Entry {
        K1 key1; ///< The row's first key.
        K2 key2; ///< The row's second key.
        T data;  ///< The row's payload.
    };

    /**
     * @brief Inserts a new row, or -- if `(key1, key2)` already exists -- replaces that row's
     *        data in place.
     *
     *        The keys themselves can't change, since together they identify the row; only
     *        `data` is replaced on conflict.
     *
     * @param key1 The row's first key.
     *
     * @param key2 The row's second key.
     *
     * @param data The payload to store (moved from).
     *
     * @return `true` if a new row was added; `false` if an existing row's data was replaced
     *         instead.
     */
    bool insert(K1 key1, K2 key2, T data) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it != pairIndex_.end()) {
            storage_[it->second].data = std::move(data);
            return false;
        }

        std::size_t idx = storage_.size();
        storage_.push_back(Entry{key1, key2, std::move(data)});
        pairIndex_.emplace(PairKey{key1, key2}, idx);
        key1Index_[key1].push_back(idx);
        key2Index_[key2].push_back(idx);
        return true;
    }

    /**
     * @brief Like insert(), but constructs `T` in place from the given arguments instead of
     *        requiring the caller to build a `T` and hand it over.
     *
     *        Useful when `T` is expensive to move/copy or has no convenient default/copy
     *        construction path, e.g. `table.emplace(k1, k2, arg1, arg2)` instead of
     *        `table.insert(k1, k2, T(arg1, arg2))`.
     *
     *        If `(key1, key2)` already exists, the existing row's data is replaced with a
     *        freshly-constructed `T(args...)`.
     *
     * @tparam Args Constructor argument types, forwarded to `T`.
     *
     * @param key1 The row's first key.
     *
     * @param key2 The row's second key.
     *
     * @param args Arguments forwarded to `T`'s constructor.
     *
     * @return `true` if a new row was added; `false` if an existing row's data was replaced
     *         instead.
     */
    template <typename... Args>
    bool emplace(K1 key1, K2 key2, Args&&... args) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it != pairIndex_.end()) {
            storage_[it->second].data = T(std::forward<Args>(args)...);
            return false;
        }

        std::size_t idx = storage_.size();
        storage_.push_back(Entry{key1, key2, T(std::forward<Args>(args)...)});
        pairIndex_.emplace(PairKey{key1, key2}, idx);
        key1Index_[key1].push_back(idx);
        key2Index_[key2].push_back(idx);
        return true;
    }

    /**
     * @brief Exact match on both keys -- the "primary key" lookup (const overload).
     *
     * @param key1 The row's first key.
     *
     * @param key2 The row's second key.
     *
     * @return A pointer to the matching Entry, or `nullptr` if not found.
     */
    const Entry* find(K1 key1, K2 key2) const {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it == pairIndex_.end()) return nullptr;
        return &storage_[it->second];
    }

    /**
     * @brief Exact match on both keys -- the "primary key" lookup (mutable overload).
     *
     * @param key1 The row's first key.
     *
     * @param key2 The row's second key.
     *
     * @return A pointer to the matching Entry, or `nullptr` if not found.
     */
    Entry* find(K1 key1, K2 key2) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it == pairIndex_.end()) return nullptr;
        return &storage_[it->second];
    }

    /**
     * @brief Returns a read-only view over all rows sharing this key1 value (const overload).
     *        Nothing is copied or allocated to build the view -- see DualKeyTableEntryView.
     *
     * @param key1 The key1 value to match.
     *
     * @return A DualKeyTableEntryView<const Entry> over every matching row. Empty if none
     *         match.
     */
    DualKeyTableEntryView<const Entry> findByKey1(K1 key1) const {
        auto it = key1Index_.find(key1);
        if (it == key1Index_.end()) return DualKeyTableEntryView<const Entry>();
        return DualKeyTableEntryView<const Entry>(it->second, &storage_);
    }

    /**
     * @brief Returns a view over all rows sharing this key1 value (mutable overload), for
     *        in-place modification of every matching row. Nothing is copied or allocated to
     *        build the view -- see DualKeyTableEntryView.
     *
     * @param key1 The key1 value to match.
     *
     * @return A DualKeyTableEntryView<Entry> over every matching row. Empty if none match.
     */
    DualKeyTableEntryView<Entry> findByKey1(K1 key1) {
        auto it = key1Index_.find(key1);
        if (it == key1Index_.end()) return DualKeyTableEntryView<Entry>();
        return DualKeyTableEntryView<Entry>(it->second, &storage_);
    }

    /**
     * @brief Returns a read-only view over all rows sharing this key2 value (const overload).
     *        Nothing is copied or allocated to build the view -- see DualKeyTableEntryView.
     *
     * @param key2 The key2 value to match.
     *
     * @return A DualKeyTableEntryView<const Entry> over every matching row. Empty if none
     *         match.
     */
    DualKeyTableEntryView<const Entry> findByKey2(K2 key2) const {
        auto it = key2Index_.find(key2);
        if (it == key2Index_.end()) return DualKeyTableEntryView<const Entry>();
        return DualKeyTableEntryView<const Entry>(it->second, &storage_);
    }

    /**
     * @brief Returns a view over all rows sharing this key2 value (mutable overload), for
     *        in-place modification of every matching row. Nothing is copied or allocated to
     *        build the view -- see DualKeyTableEntryView.
     *
     * @param key2 The key2 value to match.
     *
     * @return A DualKeyTableEntryView<Entry> over every matching row. Empty if none match.
     */
    DualKeyTableEntryView<Entry> findByKey2(K2 key2) {
        auto it = key2Index_.find(key2);
        if (it == key2Index_.end()) return DualKeyTableEntryView<Entry>();
        return DualKeyTableEntryView<Entry>(it->second, &storage_);
    }

    /**
     * @brief Checks whether a row exists for this exact `(key1, key2)`.
     *
     * @param key1 The row's first key.
     *
     * @param key2 The row's second key.
     *
     * @return `true` if a matching row exists.
     */
    bool contains(K1 key1, K2 key2) const {
        return pairIndex_.find(PairKey{key1, key2}) != pairIndex_.end();
    }

    /**
     * @class KeyProxy
     *
     * @brief Proxy returned by `DualKeyTable::operator[](K1)`, whose own `operator[](K2)`
     *        performs the real find-or-create lookup.
     *
     *        Plain `operator[](K1, K2)` with two separate arguments isn't valid before C++23's
     *        multidimensional subscript operator, so `table[key1]` returns a KeyProxy, and
     *        `proxy[key2]` completes the lookup -- the call-site syntax `table[key1][key2]` is
     *        unaffected either way.
     */
    class KeyProxy {
    public:
        /**
         * @brief Finds or default-constructs the row for `(key1, key2)`.
         *
         * @param key2 The second key, paired with the key1 captured by the enclosing `table[key1]`
         *             call.
         *
         * @return A reference to the row's data.
         */
        T& operator[](K2 key2) { return table_.getOrCreate(key1_, key2); }
    private:
        friend class DualKeyTable;
        KeyProxy(DualKeyTable& table, K1 key1) : table_(table), key1_(key1) {}
        DualKeyTable& table_;
        K1 key1_;
    };

    /**
     * @brief `std::unordered_map`-style lookup: `table[key1][key2]` returns a reference to the
     *        row's data, default-constructing a new row (with `T{}`) if `(key1, key2)` doesn't
     *        already exist -- ready for you to assign into.
     *
     *        @code
     *            table[1][100] = Row{"alice", 42.5};
     *            table[1][100].amount += 10;  // modifies in place if it already existed
     *        @endcode
     *
     * @note Requires `T` to be default-constructible (same requirement `std::unordered_map`'s
     *       `operator[]` has on its mapped type).
     *
     * @param key1 The row's first key.
     *
     * @return A KeyProxy; apply `[key2]` to it to complete the lookup.
     */
    KeyProxy operator[](K1 key1) { return KeyProxy(*this, key1); }

    /**
     * @brief Removes the row with this exact `(key1, key2)`.
     *
     * @param key1 The row's first key.
     *
     * @param key2 The row's second key.
     *
     * @return `true` if a row was found and removed; `false` if no such row existed.
     */
    bool erase(K1 key1, K2 key2) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it == pairIndex_.end()) return false;

        std::size_t idx = it->second;
        removeFromIndex(key1Index_[storage_[idx].key1], idx);
        if (key1Index_[storage_[idx].key1].empty()) key1Index_.erase(storage_[idx].key1);
        removeFromIndex(key2Index_[storage_[idx].key2], idx);
        if (key2Index_[storage_[idx].key2].empty()) key2Index_.erase(storage_[idx].key2);
        pairIndex_.erase(it);

        std::size_t lastIdx = storage_.size() - 1;
        if (idx != lastIdx) {
            storage_[idx] = std::move(storage_[lastIdx]);
            // The moved row's own index entries currently point at lastIdx; fix them to idx.
            pairIndex_[PairKey{storage_[idx].key1, storage_[idx].key2}] = idx;
            replaceInIndex(key1Index_[storage_[idx].key1], lastIdx, idx);
            replaceInIndex(key2Index_[storage_[idx].key2], lastIdx, idx);
        }
        storage_.pop_back();
        return true;
    }

    /**
     * @brief Returns the number of rows currently stored.
     *
     * @return The row count.
     */
    std::size_t size() const { return storage_.size(); }

    /**
     * @brief Checks whether the table has any rows.
     *
     * @return `true` if the table has no rows.
     */
    bool empty() const { return storage_.empty(); }

    /**
     * @brief Returns a read-only, non-owning view over every distinct key1 value currently in
     *        use by at least one row (effectively `SELECT DISTINCT key1` over the table),
     *        without copying the keys into a new container.
     *
     *        @code
     *            for (K1 k : table.allKeys1()) { ... }
     *        @endcode
     *
     * @note Order is unspecified (driven by the underlying hash map). See DualKeyTableKeyView
     *       for lifetime/invalidation notes.
     *
     * @return A DualKeyTableKeyView<K1> over the distinct key1 values.
     */
    DualKeyTableKeyView<K1> allKeys1() const { return DualKeyTableKeyView<K1>(key1Index_); }

    /**
     * @brief Same as allKeys1(), but for key2 (`SELECT DISTINCT key2`).
     *
     * @return A DualKeyTableKeyView<K2> over the distinct key2 values.
     */
    DualKeyTableKeyView<K2> allKeys2() const { return DualKeyTableKeyView<K2>(key2Index_); }

    /**
     * @brief Removes all rows, resetting the table to empty.
     *
     *        This calls `clear()` on the underlying vector/hash maps, which destroys
     *        all elements but typically keeps their allocated capacity -- convenient
     *        if you plan to refill the table afterward, since it avoids reallocation.
     *        If you want to release memory too, replace the table with a fresh one
     *        instead: `table = DualKeyTable<K1, K2, T>{};`
     */
    void clear() {
        storage_.clear();
        pairIndex_.clear();
        key1Index_.clear();
        key2Index_.clear();
    }

    /**
     * @brief Returns an iterator to the first row.
     *
     * @return An iterator to the first row. Order shifts on erase() (swap-and-pop).
     */
    auto begin() const { return storage_.begin(); }
    auto begin() { return storage_.begin(); }

    /**
     * @brief Returns an iterator one past the last row.
     *
     * @return The end iterator.
     */
    auto end() const { return storage_.end(); }
    auto end() { return storage_.end(); }

private:
    // Finds the row for (key1, key2), or default-constructs and inserts one
    // (with T{}) if it doesn't exist yet. Backs operator[].
    T& getOrCreate(K1 key1, K2 key2) {
        static_assert(std::is_default_constructible<T>::value,
                      "T must be default-constructible to use operator[] (same "
                      "requirement std::unordered_map has on its mapped type)");

        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it != pairIndex_.end()) return storage_[it->second].data;

        std::size_t idx = storage_.size();
        storage_.push_back(Entry{key1, key2, T{}});
        pairIndex_.emplace(PairKey{key1, key2}, idx);
        key1Index_[key1].push_back(idx);
        key2Index_[key2].push_back(idx);
        return storage_[idx].data;
    }

    struct PairKey {
        K1 k1;
        K2 k2;
        bool operator==(const PairKey& o) const { return k1 == o.k1 && k2 == o.k2; }
    };
    struct PairKeyHash {
        std::size_t operator()(const PairKey& p) const noexcept {
            // boost::hash_combine-style mix -- safe regardless of K1/K2 width or
            // signedness, unlike packing both values into one word via shifting.
            std::size_t h1 = std::hash<K1>{}(p.k1);
            std::size_t h2 = std::hash<K2>{}(p.k2);
            return h1 ^ (h2 + 0x9e3779b97f4a7c15ULL + (h1 << 6) + (h1 >> 2));
        }
    };

    std::vector<Entry> storage_;
    std::unordered_map<PairKey, std::size_t, PairKeyHash> pairIndex_;
    std::unordered_map<K1, std::vector<std::size_t>> key1Index_;
    std::unordered_map<K2, std::vector<std::size_t>> key2Index_;

    static void removeFromIndex(std::vector<std::size_t>& v, std::size_t idx) {
        auto it = std::find(v.begin(), v.end(), idx);
        if (it != v.end()) {
            *it = v.back();
            v.pop_back();
        }
    }
    static void replaceInIndex(std::vector<std::size_t>& v, std::size_t oldIdx, std::size_t newIdx) {
        for (auto& x : v) {
            if (x == oldIdx) { x = newIdx; break; }
        }
    }
};

/* ---------------- example usage ----------------

struct Row { std::string name; double amount; };

// Both keys the same type:
DualKeyTable<int, int, Row> table;
table.insert(1, 100, Row{"alice", 42.5});
table.insert(1, 200, Row{"bob",   17.0});
table.insert(2, 100, Row{"carol", 9.99});

if (auto* e = table.find(1, 100)) {
    // exact row: alice
}

for (const auto& e : table.findByKey1(1)) {
    // all rows with key1 == 1: alice, bob -- iterated directly off the
    // per-key index vector, no vector<Entry*> allocated to hold the results
}

for (auto& e : table.findByKey1(1)) {
    // non-const overload: mutate rows in place, e.g. bulk-adjust every
    // row sharing key1 == 1 without knowing their key2 values individually
    // e.data.amount *= 1.1;
}

for (const auto& e : table.findByKey2(100)) {
    // all rows with key2 == 100: alice, carol
}

table.emplace(3, 400, "erin", 5.5); // constructs Row{"erin", 5.5} in place

table.insert(1, 100, Row{"alice2", 50.0}); // (1,100) already exists -> replaces
                                            // alice's data, returns false

table.erase(1, 200); // removes bob

table.clear(); // table.size() == 0, all rows gone

// operator[] -- like std::unordered_map, finds or default-constructs:
table.insert(1, 100, Row{"alice", 42.5});
table[1][100].amount += 10;       // existing row: amount becomes 52.5
table[9][900] = Row{"gina", 1.0}; // no such row yet: default-constructs Row{},
                                   // inserts it, then assigns over it

for (int k1 : table.allKeys1()) {
    // every distinct key1 currently in use, e.g. 1, 2, 3, 9 -- iterated
    // directly off the internal index, nothing copied into a vector
}
for (int k2 : table.allKeys2()) {
    // every distinct key2 currently in use, e.g. 100, 200, 400, 900
}

// Mixed key types are fine too -- e.g. a small dense id alongside a pointer-sized handle:
DualKeyTable<std::uint32_t, std::uintptr_t, Row> mixedTable;
mixedTable.insert(7u, reinterpret_cast<std::uintptr_t>(somePtr), Row{"frank", 1.0});

// A non-integer key type fails to compile with a clear message:
// DualKeyTable<std::string, int, Row> badTable; // static_assert fires on K1

------------------------------------------------- */

} //?namespace rtl
} //?namespace scabbard
