/**
 * @file DualKeyTable.hpp
 * @author osterhoutan (osterhoutan+scabbard@gmail.com)
 * @brief a data structure that allows for a dual key lookup of a entry in a table, 
 *        but also to get all entries just under one key.
 *        \em NOTE: this data structure was generated by Claude Sonnet 5
 * @version alpha 0.0.1
 * @date 2026-08-27
 * 
 */

#pragma once

#include <vector>
#include <unordered_map>
#include <algorithm>
#include <cstdint>
#include <optional>
#include <utility>

namespace scabbard{
namespace rtl {

// DualKeyTable<T>
//
// Behaves like a single SQL table where:
//   - (key1, key2) together are the unique primary key. insert()/emplace() on
//     an existing (key1, key2) replace that row's data (like SQL's
//     INSERT ... ON CONFLICT ... DO UPDATE / insert_or_assign) rather than
//     failing or creating a duplicate.
//   - key1 alone can repeat across many rows -> findByKey1() returns all matches
//   - key2 alone can repeat across many rows -> findByKey2() returns all matches
//
// Complexity (average case, hash maps assumed well distributed):
//   insert          O(1)
//   emplace         O(1)
//   find(k1,k2)     O(1)
//   findByKey1(k1)  O(1) + O(m) to copy m matching pointers
//   findByKey2(k2)  O(1) + O(m) to copy m matching pointers
//   erase(k1,k2)    O(1) amortized (swap-and-pop; a couple of small vector removals)
//
// Storage is a single contiguous std::vector<Entry>, so iterating all rows,
// or scanning matches, is cache-friendly. Pointers/references into the table
// are invalidated by insert() (vector may reallocate) and by erase() (the
// last element gets moved into the erased slot). If you need stable
// addresses across mutation, change `storage_` to std::deque<Entry> --
// everything else still works unmodified.

template <typename T>
class DualKeyTable {
public:
    struct Entry {
        std::uintptr_t key1;
        std::uintptr_t key2;
        T data;
    };

    // Inserts a new row, or -- if (key1, key2) already exists -- replaces that
    // row's data in place (the keys themselves can't change, since they're
    // what identifies the row). Returns true if a new row was added, false if
    // an existing row's data was replaced.
    bool insert(std::uintptr_t key1, std::uintptr_t key2, T data) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it != pairIndex_.end()) {
            storage_[it->second].data = std::move(data);
            return false;
        }

        std::size_t idx = storage_.size();
        storage_.push_back(Entry{key1, key2, std::move(data)});
        pairIndex_.emplace(PairKey{key1, key2}, idx);
        key1Index_[key1].push_back(idx);
        key2Index_[key2].push_back(idx);
        return true;
    }

    // Like insert(), but constructs T in place from the given arguments instead
    // of requiring the caller to build a T and hand it over. Useful when T is
    // expensive to move/copy or has no convenient default/copy construction path,
    // e.g. table.emplace(k1, k2, arg1, arg2) instead of
    //      table.insert(k1, k2, T(arg1, arg2)).
    // If (key1, key2) already exists, the existing row's data is replaced with
    // a freshly-constructed T(args...). Returns true if a new row was added,
    // false if an existing row's data was replaced.
    template <typename... Args>
    bool emplace(std::uintptr_t key1, std::uintptr_t key2, Args&&... args) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it != pairIndex_.end()) {
            storage_[it->second].data = T(std::forward<Args>(args)...);
            return false;
        }

        std::size_t idx = storage_.size();
        storage_.push_back(Entry{key1, key2, T(std::forward<Args>(args)...)});
        pairIndex_.emplace(PairKey{key1, key2}, idx);
        key1Index_[key1].push_back(idx);
        key2Index_[key2].push_back(idx);
        return true;
    }

    // Exact match on both keys -- the "primary key" lookup.
    const Entry* find(std::uintptr_t key1, std::uintptr_t key2) const {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it == pairIndex_.end()) return nullptr;
        return &storage_[it->second];
    }
    Entry* find(std::uintptr_t key1, std::uintptr_t key2) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it == pairIndex_.end()) return nullptr;
        return &storage_[it->second];
    }

    // All rows sharing this key1 value.
    std::vector<const Entry*> findByKey1(std::uintptr_t key1) const { return collect(key1Index_, key1); }
    // All rows sharing this key2 value.
    std::vector<const Entry*> findByKey2(std::uintptr_t key2) const { return collect(key2Index_, key2); }

    bool contains(std::uintptr_t key1, std::uintptr_t key2) const {
        return pairIndex_.find(PairKey{key1, key2}) != pairIndex_.end();
    }

    // Removes the row with this exact (key1, key2). Returns false if not found.
    bool erase(std::uintptr_t key1, std::uintptr_t key2) {
        auto it = pairIndex_.find(PairKey{key1, key2});
        if (it == pairIndex_.end()) return false;

        std::size_t idx = it->second;
        removeFromIndex(key1Index_[storage_[idx].key1], idx);
        removeFromIndex(key2Index_[storage_[idx].key2], idx);
        pairIndex_.erase(it);

        std::size_t lastIdx = storage_.size() - 1;
        if (idx != lastIdx) {
            storage_[idx] = std::move(storage_[lastIdx]);
            // The moved row's own index entries currently point at lastIdx; fix them to idx.
            pairIndex_[PairKey{storage_[idx].key1, storage_[idx].key2}] = idx;
            replaceInIndex(key1Index_[storage_[idx].key1], lastIdx, idx);
            replaceInIndex(key2Index_[storage_[idx].key2], lastIdx, idx);
        }
        storage_.pop_back();
        return true;
    }

    std::size_t size() const { return storage_.size(); }
    bool empty() const { return storage_.empty(); }

    // Full-table iteration, in insertion-ish order (order shifts on erase due to swap-and-pop).
    auto begin() const { return storage_.begin(); }
    auto end() const { return storage_.end(); }

private:
    struct PairKey {
        std::uintptr_t k1, k2;
        bool operator==(const PairKey& o) const { return k1 == o.k1 && k2 == o.k2; }
    };
    struct PairKeyHash {
        std::size_t operator()(const PairKey& p) const noexcept {
            // boost::hash_combine-style mix -- safe regardless of uintptr_t width,
            // unlike packing both values into one word via shifting.
            std::size_t h1 = std::hash<std::uintptr_t>{}(p.k1);
            std::size_t h2 = std::hash<std::uintptr_t>{}(p.k2);
            return h1 ^ (h2 + 0x9e3779b97f4a7c15ULL + (h1 << 6) + (h1 >> 2));
        }
    };

    std::vector<Entry> storage_;
    std::unordered_map<PairKey, std::size_t, PairKeyHash> pairIndex_;
    std::unordered_map<std::uintptr_t, std::vector<std::size_t>> key1Index_;
    std::unordered_map<std::uintptr_t, std::vector<std::size_t>> key2Index_;

    std::vector<const Entry*> collect(const std::unordered_map<std::uintptr_t, std::vector<std::size_t>>& idxMap,
                                       std::uintptr_t key) const {
        std::vector<const Entry*> result;
        auto it = idxMap.find(key);
        if (it != idxMap.end()) {
            result.reserve(it->second.size());
            for (std::size_t i : it->second) result.push_back(&storage_[i]);
        }
        return result;
    }

    static void removeFromIndex(std::vector<std::size_t>& v, std::size_t idx) {
        auto it = std::find(v.begin(), v.end(), idx);
        if (it != v.end()) {
            *it = v.back();
            v.pop_back();
        }
    }
    static void replaceInIndex(std::vector<std::size_t>& v, std::size_t oldIdx, std::size_t newIdx) {
        for (auto& x : v) {
            if (x == oldIdx) { x = newIdx; break; }
        }
    }
};

/* ---------------- example usage ----------------

struct Row { std::string name; double amount; };

DualKeyTable<Row> table;
table.insert(1, 100, Row{"alice", 42.5});   // std::uintptr_t keys -- plain integer literals
table.insert(1, 200, Row{"bob",   17.0});   // still work fine and convert implicitly
table.insert(2, 100, Row{"carol", 9.99});
table.insert(reinterpret_cast<std::uintptr_t>(somePtr), 300, Row{"dave", 3.0}); // or actual pointers

table.emplace(3, 400, "erin", 5.5); // constructs Row{"erin", 5.5} in place

table.insert(1, 100, Row{"alice2", 50.0}); // (1,100) already exists -> replaces
                                            // alice's data, returns false


if (auto* e = table.find(1, 100)) {
    // exact row: alice
}

for (auto* e : table.findByKey1(1)) {
    // all rows with key1 == 1: alice, bob
}

for (auto* e : table.findByKey2(100)) {
    // all rows with key2 == 100: alice, carol
}

table.erase(1, 200); // removes bob

------------------------------------------------- */



} //?namespace rtl
} //?namespace scabbard
